//! Typed, layout-free contract between the deterministic VM and a game UI.
//!
//! The core owns narrative state and validates semantic intents. A host owns
//! DOM layout, hit testing, focus, styling, and accessibility. Keeping those
//! responsibilities apart prevents a second UI DSL from growing inside the
//! bytecode format.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::vm::{AutoMode, SettingsState, SkipMode};

/// Version of the JSON view contract consumed by game presentation packages.
///
/// Schema 6 pages subtitles in Core, exposes replayable backlog page IDs,
/// persists semantic gallery/confirmation/interlude state, and carries the
/// reader's subtitle-opacity/stage-effects preferences without coupling a
/// host to DOM layout.
pub const UI_VIEW_MODEL_SCHEMA: u16 = 6;

/// Standard surfaces understood by the engine. A frontend may render a
/// project-specific surface for [`Self::Custom`] without changing the VM
/// layout protocol.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", content = "name", rename_all = "snake_case")]
pub enum UiRoute {
    Setup,
    Title,
    /// A self-contained endpoint for a content-limited public build. It is
    /// a base route rather than an overlay, so restoring a save preserves
    /// the fact that the trial has ended.
    DemoEnd,
    Dialogue,
    Pause,
    Save,
    Load,
    Settings,
    Backlog,
    ChapterSelect,
    Gallery,
    Confirm,
    Custom(String),
}

impl UiRoute {
    #[must_use]
    pub fn parse(value: &str) -> Self {
        match value {
            "setup" => Self::Setup,
            "title" => Self::Title,
            "demo_end" => Self::DemoEnd,
            "dialogue" => Self::Dialogue,
            "pause" => Self::Pause,
            "save" => Self::Save,
            "load" => Self::Load,
            "settings" => Self::Settings,
            "backlog" => Self::Backlog,
            "chapter_select" => Self::ChapterSelect,
            "gallery" => Self::Gallery,
            "confirm" => Self::Confirm,
            other => Self::Custom(other.to_owned()),
        }
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Setup => "setup",
            Self::Title => "title",
            Self::DemoEnd => "demo_end",
            Self::Dialogue => "dialogue",
            Self::Pause => "pause",
            Self::Save => "save",
            Self::Load => "load",
            Self::Settings => "settings",
            Self::Backlog => "backlog",
            Self::ChapterSelect => "chapter_select",
            Self::Gallery => "gallery",
            Self::Confirm => "confirm",
            Self::Custom(value) => value,
        }
    }

    #[must_use]
    pub const fn is_overlay(&self) -> bool {
        matches!(
            self,
            Self::Pause
                | Self::Save
                | Self::Load
                | Self::Settings
                | Self::Backlog
                | Self::ChapterSelect
                | Self::Gallery
                | Self::Confirm
        )
    }
}

/// A semantic input generated by a presentation package. It carries no pixel
/// coordinates, DOM selector, or visual style.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum UiIntent {
    Activate { id: String },
    OpenRoute { route: String },
    Dismiss,
    SetSetting { name: String, value: f32 },
    ToggleSetting { name: String },
    Scroll { region: String, delta_y: f32 },
}

/// Stable game identity and locale consumed by the presentation package.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GameView {
    pub id: String,
    pub locale: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DialogueView {
    pub speaker: Option<String>,
    /// The complete authored line. It remains available for transcript tools,
    /// while the reading surface should use `full_page_text` and `text`.
    pub full_text: String,
    /// The complete current subtitle page, including deterministic explicit
    /// line breaks. `text` is its currently revealed prefix.
    pub full_page_text: String,
    /// One-based page position within `full_text`.
    pub page_number: u32,
    pub page_count: u32,
    /// Stable identifier used by history/replay. It carries no DOM identity.
    pub page_id: String,
    /// Width of the deterministic subtitle grid in display cells.
    pub columns: u16,
    pub text: String,
    pub complete: bool,
    pub awaiting_advance: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChoiceView {
    pub id: String,
    pub label: String,
    pub selected: bool,
}

/// An action supplied by the engine. Its display label belongs to the game
/// frontend's locale catalog, not to a renderer baked into ARIAC.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionView {
    pub id: String,
    pub enabled: bool,
    #[serde(default)]
    pub active: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BacklogEntryView {
    pub id: String,
    /// Stable page target accepted by the resume confirmation flow.
    pub resume_id: String,
    pub speaker: Option<String>,
    pub text: String,
    pub locale: String,
    pub timestamp_ms: u64,
    pub selected: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChapterView {
    pub id: String,
    pub title: String,
    pub description: String,
    pub thumbnail: Option<String>,
    pub script: Option<String>,
    pub unlocked: bool,
    pub progress: u8,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GalleryItemView {
    pub id: String,
    pub unlocked: bool,
    pub selected: bool,
}

/// Timing identity for a story-owned interlude. The host still owns the fade
/// curve; Core only tells it whether this is the first held encounter so a
/// restored save keeps the same authored silence.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InterludeView {
    pub first_visit: bool,
}

/// A destructive presentation action that must be explicitly acknowledged.
/// The frontend owns the words and visual treatment; the VM owns which
/// action is pending so a confirmation cannot be forged or lost on save.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConfirmationView {
    pub action: String,
    pub resume_id: Option<String>,
}

/// The complete non-visual state for one React/UI update.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UiViewModel {
    pub schema_version: u16,
    pub route: UiRoute,
    pub route_stack: Vec<UiRoute>,
    pub game: GameView,
    pub dialogue: Option<DialogueView>,
    pub choices: Vec<ChoiceView>,
    pub actions: Vec<ActionView>,
    pub settings: SettingsState,
    /// Only a virtual window is populated while the backlog route is open.
    /// A normal reading update therefore never clones or serializes the full
    /// history merely because another grapheme appeared.
    pub backlog: Vec<BacklogEntryView>,
    pub backlog_total: u32,
    pub backlog_start: u32,
    pub chapters: Vec<ChapterView>,
    pub gallery: Vec<GalleryItemView>,
    pub gallery_viewer: Option<String>,
    pub interlude: Option<InterludeView>,
    pub confirmation: Option<ConfirmationView>,
    pub scroll_offsets: BTreeMap<String, f32>,
    pub auto_mode: AutoMode,
    pub skip_mode: SkipMode,
    pub reduced_motion: bool,
}
